# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Build Application
      run: npm run build

    - name: Start Backend and Test
      run: npm run start-backend

    - name: Deploy to Vercel
      env:
        GH_API_KEY: ${{ github.secret_source.GH_API_KEY }}
        NEON_API_KEY: ${{ github.secret_source.NEON_API_KEY }}
        VERCEL_TOKEN: ${{ github.secret_source.VERCEL_TOKEN }}
      run: npx vercel --prod

  create-neon-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Create Neon Branch
      uses: neondatabase/create-branch-action@v5
      with:
        project_id: rapid-haze-373089
        parent: main
        database: t3-db
        branch_name: dev-branch
        username: t3-db_owner
        api_key: ${{ secrets.NEON_API_KEY }}

  delete-neon-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Delete Neon Branch
      uses: neondatabase/delete-branch-action@v3
      with:
        project_id: rapid-haze-373089
        branch: feature-branch
        api_key: ${{ secrets.NEON_API_KEY }}
